import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

import blogs from '../data/blogs.json'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Sample Static Blogs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>List of blogs!</h1>
      {blogs.map(blog => <Link href = {`/${blog.slug}`} key = {blog.id}>{blog.title}</Link>)}
    </div>
  )
}
